### ISSUE TITLE
There is no option to build rail road improvement when connection from a phone

### ISSUE THREAD

**Issue by alvaromongon** [freeciv/freeciv-web#146]
When connected with a phone and selecting a unit that can build terrain improvements. Then, the option to build a rail road does not appear. Therefore, it is not possible to build it.

**Comment by lonemadmax** [comment]
Cannot reproduce. I have even borrowed a small real phone and it works for me. The only difference I've found in code is that the context menu with the actions is somewhat bigger in mobile (well, touch devices and small screens), which might lead to some of the actions overflowing the screen, but build railroad is at the top, just in the same place build road is if there's no road.

**Comment by alvaromongon** [comment]
I can reproduce it in safari, chrome and Firefox. But It happens when you can build railroad, but you are missing other tech I could not determine. My theory is that some other tech later modify the drop down menu and then the rail road appear. Here you have an example:

![image](https://user-images.githubusercontent.com/18199789/35192456-0644ec02-fe93-11e7-8417-4983fb31629e.png)

**Comment by lonemadmax** [comment]
The tech is Railroad. You also need Bridge Building to build them on river tiles, but that's not checked to show the menu. I guess you have both, if you built all those roads and railroads. Anyway, if trying with a computer works, it certainly isn't related to tech.

It might be due to differences in the handling of events in touch devices (or in timing). Maybe it's not that the menu doesn't show that option in mobile (it does for me), but that you are getting the menu of actions for a different unit (for the case in the screenshot, a worker in a tile with a railroad, maybe the one selected if it was moved from the tile to its left and the menu somehow generated with the info from there). Discarding the menu and opening it again should show the railroad option then.

Still investigating.

**Comment by alvaromongon** [comment]
I tried re-opening the menu and I also tried in mobile devices (touch), same behaviour than in the screen shoot.

If I can test something else to help you, let me know.

**Comment by ghost** [comment]
Perhaps the problem is that techs required for building railroad has a different id
in different rulesets.

See:  https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/control.js#L942

**Comment by lonemadmax** [comment]
Yup, Radio in multiplayer, if the comments in reqtree are right. Silly me, I didn't see that ruleset.
That doesn't explain the phone thing, though. @alvaromongon ,  does the same unit in the same game show the railroad action in non-mobile device? Does your phone show it in a game with non-multiplayer ruleset, if you have one?

**Comment by alvaromongon** [comment]
It does not show the action in any device.

Initially I thought it was just happening in touch devices but same thing
happens in all devices. At least for multiplayer games.

I do not have any single player game.

**Comment by alvaromongon** [comment]
Great, Thank you!
