### ISSUE TITLE
Production menu is laggy

### ISSUE THREAD

**Issue by dareg** [freeciv/freeciv-web#154]
Since today I have observed that the production menu of the cities is very slow. Every time I click somewhere in this menu, the action is delayed by some seconds. And sometimes firefox warn me that a script is too slow and ask me if I want to continue or just stop it.
Firefox says it's because of this script: 
Script : https://play.freeciv.org/javas…jquery.min.js?ts=20180121-1549:3

**Comment by lonemadmax** [comment]
This is because of 60eafc2137074b2778611fd4f4ce2773da633a23
I can't do anything until at least tomorrow, so @andreasrosdal, if it's too annoying, please just revert that.
Current fast options:
- Revert and lose doubleclick
- Just remove the redraw and lose the map in the canvas while the dialog is open.
- Keep the  current slow thing.

There's no real window size change when opening the dialog, so maybe removing the redraw and adding a check in set_window_size to only touch the canvas when needed would be enough. When I tried a naive check, I  got bigger issues.

**Comment by ghost** [comment]
Okay, reverted.
