### ISSUE TITLE
The Docker image fails to build due to an error related to Linux LSB

### ISSUE THREAD

**Issue by doctorpangloss** [freeciv/freeciv-web#165]
After @7d6a6929d330ecf44, which is the commit just before the common install script, the script fails inside Docker with the following error message:

```
Step 24/26 : RUN install/install.sh
 ---> Running in 3952cefbf2ab
=================================
Running Freeciv-web setup script.
=================================

Linux 3952cefbf2ab 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux
basedir: /docker
No LSB modules are available.
Distributor ID:    Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:    9.4
Codename:    stretch

Please copy scripts/configuration.sh.dist to scripts/configuration.sh and
edit its content to suit your needs.
The command '/bin/sh -c install/install.sh' returned a non-zero code: 4
```

**Comment by lonemadmax** [comment]
The `No LSB modules are available.` is just a message about available LSB modules. It's OK that there are none.

The real problem is:
`Please copy scripts/configuration.sh.dist to scripts/configuration.sh and
edit its content to suit your needs.`
You have to setup `scripts/configuration.sh` and `freeciv-web/src/main/webapp/WEB-INF/config.properties` before installing. In most cases you'd just copy the `.dist` files and not touch anything.
