### ISSUE TITLE
Keep source directories clean of build artifacts

### ISSUE THREAD

**Issue by mchenryc** [freeciv/freeciv-web#182]
During the build, many files are generated directly into the same directory as source controlled. This adds noise to the repository, making a "clean build" error prone, and risks the commit of one of these generated files.

These are mostly derived from upstream freeciv, via python and shell scripts during the general install (see [scripts/install/install.sh](https://github.com/freeciv/freeciv-web/blob/develop/scripts/install/install.sh)), which doesn't play particularly well with maven expectations.

Many generated files are source files which need to be known to IDEs (and thus "easier" to work with when generated to source directories), while others are images, HTML help files, and other resources that are just as easily generated to a target/build/dest directory.

The hope then, is that after running an install/build, the following will hold true:
* `git status` will show no changed or untracked files after full build, and test.
* maintain simplicity of overall build/dev lifecycle with Vagrant
* incremental builds of the webapp will (continue to) not need to regenerate derived files

**Comment by lonemadmax** [comment]
gitignore (test that the git magic used to download just the new stuff and not the whole history when updating freeciv server still works):
```
freeciv-web/src/main/webapp/docs/LICENSE.txt
pbem/pbem-games.json
tests/casperjs-1.1.4/
freeciv/freeciv/
```

These are sources generated from freeciv code and may have to be regenerated (running `scripts/sync-js-hand.sh`) every time the freeciv code is updated. They should be gitignored, maybe dumped into a generated-sources directory to separate them from stuff one may touch:
```
freeciv-web/src/main/webapp/javascript/2dcanvas/tileset_spec_amplio2.js
freeciv-web/src/main/webapp/javascript/2dcanvas/tileset_spec_isotrident.js
freeciv-web/src/main/webapp/javascript/2dcanvas/tileset_spec_trident.js
freeciv-web/src/main/webapp/javascript/fc_events.js
freeciv-web/src/main/webapp/javascript/freeciv-helpdata.js
freeciv-web/src/main/webapp/javascript/packets.js
freeciv-web/src/main/webapp/javascript/packhand_gen.js
freeciv-web/src/main/webapp/javascript/soundset_spec.js
```

Source generated from handlebars templates, already in the pom. Again, gitignore and maybe put in a generated sources directory:
`freeciv-web/src/main/webapp/javascript/hbs-templates.js`

These are related to the other big block of server sync. Some should be moved to the sources directories instead of copied, some should be deleted after finishing with them, and all the work should probably be done in a tmp directory instead.
```
scripts/freeciv-helpdata.js
scripts/freeciv-img-extract/amplio2
scripts/freeciv-img-extract/buildings
scripts/freeciv-img-extract/flags
scripts/freeciv-img-extract/freeciv-web-tileset-amplio2-0.png
scripts/freeciv-img-extract/freeciv-web-tileset-amplio2-1.png
scripts/freeciv-img-extract/freeciv-web-tileset-amplio2-2.png
scripts/freeciv-img-extract/freeciv-web-tileset-isotrident-0.png
scripts/freeciv-img-extract/freeciv-web-tileset-isotrident-1.png
scripts/freeciv-img-extract/freeciv-web-tileset-trident-0.png
scripts/freeciv-img-extract/freeciv-web-tileset-trident-1.png
scripts/freeciv-img-extract/isotrident
scripts/freeciv-img-extract/misc
scripts/freeciv-img-extract/tileset_spec_amplio2.js
scripts/freeciv-img-extract/tileset_spec_isotrident.js
scripts/freeciv-img-extract/tileset_spec_trident.js
scripts/freeciv-img-extract/trident
scripts/freeciv-img-extract/wonders
scripts/packets.js
scripts/packhand_gen.js
scripts/soundspec-extract/soundset_spec.js
```
