### ISSUE TITLE
Allow numbers in player names

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#183]
I see in the Track.js logs that many players try to use usernames with numbers in them, but this is not allowed and the user is given an error message. So I think Freeciv-web should allow numbers in the username. Remember to update all places where usernames are validated.

**Comment by lonemadmax** [comment]
How should they be handled?
- Remove them and don't give an error: max, max2, max42 and max1965 would be the same user.
- Change them into letters: 0scar and Oscar would be the same user.
- Just allow numbers, dammit! All previous examples would be different users.

A few weeks ago I thought about moving the checks to one place (at least the ones in the servlets), so that they'd all be the same and there were fewer places to touch. Some of them already include numbers and even spaces, while others don't. Then, as always, I wandered instead of working. Maybe I should reduce the limits to allow accented characters, I have an á in my name. But French has a few more than Spanish. And Scandinavian have a few more characters. And that's still be too latin centric. How about cyrillic? Greek? Hebrew? Arabic? CJK? ...

Last I remember I was thinking of accepting anything that consisted only of "letters" and single whitespace (and numbers now) -that is, emoji, dingbats, symbols and other such groups would give an error- and using something like ICU to transliterate for the username (that would still be lowercase a-z, or very little more), while keeping the not-just-ASCII as leader name. Thus "maximo", "Máximo" and maybe "Max Imo" would all be just one user: maximo, but may play under whichever name used to log in to a game. 文明 would be user wenming, but play as 文明 if they want. Etc.

I'll stick to the easier part of adding numbers for now, but am I too crazy if I open the whole can of worms?

**Comment by mchenryc** [comment]
Names... Always a problem :roll_eyes: You'd be surprised how many systems will still only allow capital letters as the first character of a ~~word~~ name...

Allowing numbers should be easy enough - they're still ASCII. Stake that out to begin with, and get a feel for all the parts it touches. Anything more, and you're venturing into other character sets, at which point you should just ensure UTF-8 works (otherwise you're just causing yourself headache when you want to allow _some other language's characters_ down the line).

However, ensuring UTF-8 works (or frankly, almost anything but ASCII) will likely touch everything from DB config (ensure the column is configured to store UTF-8) up to the web pages (are the character encoding and doctype correct/compatable? Is an appropriate font available?), and of course all the functions of the JS and Java... and even the Python proxy in between.

And it probably depends on what freeciv itself allows - it is old enough that it wasn't a concern when it began, so just enabling it might be quite an endeavor (but having not looked, it may already be the default :man_shrugging:).
