### ISSUE TITLE
Savegame bug

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#199]
http://forum.freeciv.org/f/viewtopic.php?f=24&t=90393

**Comment by lonemadmax** [comment]
I don't see anything. Can you check the directory permissions and acls for their users and one that works? I have successfully saved games under madmax.

**Comment by andreasrosdalw** [comment]
it seems archimedes savegame directory is owned by tomcat, while yours is owned by the freeciv user.

**Comment by lonemadmax** [comment]
With no writing permissions for "other" and also no effective acl to do so, I guess. Which would explain the server not being able to save games. What I don't know is why tomcat owns archimedes (and jacknoir and probably more?). Maybe that's how isotrident started life and the affected players are the ones that had saved games before https://github.com/Isotrident/Isotrident/commit/33b587b97814960e676f2cc1dbd69ef8ad5ce86f or some other change?

If I'm not wrong, the current setting is that webapps/data and everything below is owned by the freeciv user (maybe not hall of fame maps), with acls so that tomcat can read, write and navigate for things like getting and deleting savegames, and freeciv server creating the directories with group access to allow the acl rules do their thing.

**Comment by andreasrosdalw** [comment]
I have done some chmod on the server. seems to work.
