### ISSUE TITLE
Adding new LongTurn games at runtime

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#252]
There should be a way of adding new LongTurn games at runtime.

Currently adding new LongTurn games requires a server restart, and saving and reloading all existing LongTurn games from their savegames.

**Comment by lonemadmax** [comment]
It doesn't since e2efcb3e8341b8a80ff381b0e9f6b03267e7c4b6. Just drop a publite_longturn_*.serv file into the publite2 directory and wait about a minute. No need to reserve ports (or put them in the name, no longer bound to what's in the name).

What still needs a restart is removing games. Well, you can start a new game overwriting the serv file and killing just the server for it, but it's still cumbersome.
