### ISSUE TITLE
Special resources are not shown correctly from a loaded savegame in Freeciv-web

### ISSUE THREAD

**Issue by ghost** [freeciv/freeciv-web#41]
Special resources are not shown correctly from a loaded savegame in Freeciv-web.

http://forum.freeciv.org/f/viewtopic.php?f=24&t=3497

**Comment by ghost** [comment]
http://www.hostedredmine.com/issues/704729

**Comment by lonemadmax** [comment]
Sniffing the communication shows max_extra_types for the resources in fow tiles. That's as if there weren't any. But [the server is sending them](https://github.com/freeciv/freeciv/blob/1030d83e26ada57e624bd8f94f8213184de1da8d/server/maphand.c#L555), only getting them from the player's private map instead of the global one. The private map seems to be saved only if there's fow (unneeded if there's not) and the save_private_map option is set. I guess that's not set in fc-web games.
