### ISSUE TITLE
Moving the mouse on the map causes low frame rate

### ISSUE THREAD

**Issue by lmoureaux** [freeciv/freeciv-web#53]
The ray tracing function used to get the object under the cursor is slow (~3 frames) and significant frame rate drops. I don't know how to make something faster. Maybe we could give the tracer a hint by inverting the projection*view matrix ?

**Comment by ghost** [comment]
Thanks for reporting this! The result is much improved performance when moving the mouse!

The problem was that raycaster.intersectObjects( scene.children ) was checking for intersection against all objects in the scene. I have changed this so that it checks against the land mesh instead.

https://github.com/freeciv/freeciv-web/commit/863f4591ac47f7cd11e3b2713ce6710142a614d1#diff-74bef896d02717002640f980116dad28
